In [10]:
# check pip version
pip -V

pip 22.0.4 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)
Note: you may need to restart the kernel to use updated packages.


In [9]:
#instalasi numpy
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 883.4 kB/s eta 0:00:0000:0100:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [12]:
# menggunakan numpy
import numpy as np

In [13]:
np.array([1,2,3])

array([1, 2, 3])

In [14]:
# menggunakan from secara spesifik
from numpy import array
array([1,2,3])

array([1, 2, 3])