In [10]:
# check pip version
pip -V

pip 22.0.4 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)
Note: you may need to restart the kernel to use updated packages.


In [9]:
#instalasi numpy
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 883.4 kB/s eta 0:00:0000:0100:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [1]:
# menggunakan numpy
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# menggunakan from secara spesifik
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [4]:
import script

10 elmen didalam list tamb_kel 

isi elmen didalam list tamb_kel : 
 ['irin', 4.23, 'agus', 4.69, 'sena', 4.36, 'dian', 4.81, 'abi', 4.69]
tipe list tamb_kel :  <class 'list'>

 isi elmen didalam list np_kel : 
 ['irin' '4.23' 'agus' '4.69' 'sena' '4.36' 'dian' '4.81' 'abi' '4.69']
tipe list np_kel :  <class 'numpy.ndarray'>


In [1]:
pip install scipy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.7/28.7 MB 1.7 MB/s eta 0:00:0000:0100:01m
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
