In [2]:
import numpy as np
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(np.shape(a))
print('\n', a)

(3, 2)

 [[1 1]
 [2 2]
 [3 3]]


In [4]:
b = np.insert(a, 1, 5)
print(np.shape(b))

print('\n', b)

(7,)

 [1 5 1 2 2 3 3]


In [5]:
numpy_array = np.array([1,2,3])
print(np.shape(numpy_array))

print('\n', numpy_array)

(3,)

 [1 2 3]


In [6]:
np.insert(numpy_array, 3, 5)

array([1, 2, 3, 5])