In [1]:
# penambahan isi numpy
import numpy as np
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
# melihat ukuran array
a = np.array([[1, 1], [2, 2], [3, 3]])
print(np.shape(a))
print('\n', a)

(3, 2)

 [[1 1]
 [2 2]
 [3 3]]


In [91]:
a.shape


(3, 2)

In [3]:
# menambahkan isi array dengan spesifik posisi
a = np.array([[1, 1], [2, 2], [3, 3]])
b = np.insert(a, 1, 5)
print(np.shape(b))
print('\n', b)

(7,)

 [1 5 1 2 2 3 3]


In [68]:
# insert dengan array 1 d
numpy_array = np.array([1,2,3])
print(np.shape(numpy_array))
print('\n', numpy_array)
np.insert(numpy_array, 3, 5)

(3,)

 [1 2 3]


array([1, 2, 3, 5])

## Array 2 Dimensi

In [72]:
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_lebar = np.array([65.4, 59.2, 63.8, 88.4, 68.71])
type(np_lebar)

numpy.ndarray

In [74]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.8, 88.4, 68.71]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.8 , 88.4 , 68.71]])

In [75]:
type(np_2d)

numpy.ndarray

In [76]:
np.shape(np_2d)

(2, 5)

In [77]:
np_2d.shape

(2, 5)

In [78]:
#[1][2] dimana 1 = baris & 2 = kolom
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [79]:
np_2d[0][2]

1.71

In [80]:
np_2d[0,2]

1.71

In [81]:
#[a, b] dimana a = baris & b = kolom
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.8 ]])

In [82]:
np_2d[0,:]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [89]:
# pemanggilan secara accak di costume saja
np.array([np_2d[0,4], np_2d[1,0]])

array([ 1.79, 65.4 ])