In [1]:
import numpy as np

In [2]:
np_kota = np.array([[1.64, 71.78], [1.37, 63.35], [1.6, 55.09], [2.04, 74.85], [2.01, 73.57]])
np_kota

array([[ 1.64, 71.78],
       [ 1.37, 63.35],
       [ 1.6 , 55.09],
       [ 2.04, 74.85],
       [ 2.01, 73.57]])

In [3]:
np.shape(np_kota)

(5, 2)

In [4]:
np.mean(np_kota[:,0])

1.732

In [5]:
np.median(np_kota[:,0])

1.64

In [14]:
np.average(np_kota[:,0])

1.732

In [6]:
np.std(np_kota[:,0])

0.2565462921189857

In [15]:
np.var(np_kota[:,0])

0.06581599999999996

In [7]:
np.corrcoef(np_kota[:,0], np_kota[:,0])

array([[1., 1.],
       [1., 1.]])

In [17]:
np.cov(np_kota.T)

array([[ 0.08227,  1.67448],
       [ 1.67448, 70.03912]])

In [20]:
np.percentile(np_kota, 95)

74.27399999999999

In [22]:
from scipy import stats
stats.mode(np_kota)

ModeResult(mode=array([[ 1.37, 55.09]]), count=array([[1, 1]]))

In [23]:
contoh = np.array([1,1,2,1,3,4,5])
stats.mode(contoh)

ModeResult(mode=array([1]), count=array([3]))

In [8]:
np.sum(np_kota)

347.3

In [9]:
np.max(np_kota)

74.85

In [10]:
np.min(np_kota)

1.37